language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --verbose

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
